### ISSUE TITLE
Personal vehicles dissapear after server restart.

### ISSUE THREAD

**Issue by Kxlum** [Mono-94/mGarage#9]
Is there any way you could change it so that on server restart any player owned vehicles that get left out and not returned to garage get sent to the impound because at the moment if you leave your car out and the server restarts, the database still thinks the car is out so when you go to retrieve it doesn't let you. And then if you press GPS it will throw an error because it can't find the car.

**Comment by LikeManTV** [comment]
What framework do you use?
The vehicles should be spawned after server restart but it's not done on ox_core I believe.

**Comment by Kxlum** [comment]
Im on ESX.

**Comment by Kxlum** [comment]
Ive done multiple testing and it seems that the vehicles only get sent to the impound if there dv'd or just simply impounded, however if you restart the server or the server crashes when your vehicle is out, it doesn't tell the database to send it to the impound so the car can never be retreived. A fix would be to tell database to send to impound as soon as it leaves the garage, however could lead to duplication of vehicles at the impound. Please fix this as the rest is a really good free script thanks. :)

**Comment by Kxlum** [comment]
This shows the GT86 I left outside and when i restart the server it gets sent to nowhere.

- ![Screenshot 2024-06-03 234458](https://github.com/Mono-94/mGarage/assets/121975473/21ff6b46-a5d4-47ab-b589-6e48b0d4bead)

**Comment by Mono-94** [comment]
This is not related to the mGarage, but rather to mVehicle and you probably don't have convar set.

**Comment by Kxlum** [comment]
That was my issue, I never even knew there was a convar to set, must have missed it my bad, issue fixed thanks!
